package bd.com.albin.tasks.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF003399)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDFE0FF)
val md_theme_light_onPrimaryContainer = Color(0xFF000B62)
val md_theme_light_secondary = Color(0xFF3A6A00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF92FD14)
val md_theme_light_onSecondaryContainer = Color(0xFF0D2000)
val md_theme_light_tertiary = Color(0xFF006688)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC2E8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7FFEC)
val md_theme_light_onBackground = Color(0xFF082100)
val md_theme_light_surface = Color(0xFFF7FFEC)
val md_theme_light_onSurface = Color(0xFF082100)
val md_theme_light_surfaceVariant = Color(0xFF705947)
val md_theme_light_onSurfaceVariant = Color(0xFFFFBF00)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_inverseOnSurface = Color(0xFFCEFFAE)
val md_theme_light_inverseSurface = Color(0xFF133800)
val md_theme_light_inversePrimary = Color(0xFFF57F17)
val md_theme_light_surfaceTint = Color(0xFF2843F9)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFDCDC3C)
val md_theme_dark_onPrimary = Color(0xFF00189A)
val md_theme_dark_primaryContainer = Color(0xFF0025D7)
val md_theme_dark_onPrimaryContainer = Color(0xFFDFE0FF)
val md_theme_dark_secondary = Color(0xFF7EDE00)
val md_theme_dark_onSecondary = Color(0xFF1B3700)
val md_theme_dark_secondaryContainer = Color(0xFF2A5000)
val md_theme_dark_onSecondaryContainer = Color(0xFF92FD14)
val md_theme_dark_tertiary = Color(0xFF76D1FF)
val md_theme_dark_onTertiary = Color(0xFF003548)
val md_theme_dark_tertiaryContainer = Color(0xFF004D67)
val md_theme_dark_onTertiaryContainer = Color(0xFFC2E8FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF082100)
val md_theme_dark_onBackground = Color(0xFFB9F396)
val md_theme_dark_surface = Color(0xFF082100)
val md_theme_dark_onSurface = Color(0xFFB9F396)
val md_theme_dark_surfaceVariant = Color(0xFF4F5270)
val md_theme_dark_onSurfaceVariant = Color(0xFFFFBF00)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_inverseOnSurface = Color(0xFF082100)
val md_theme_dark_inverseSurface = Color(0xFFB9F396)
val md_theme_dark_inversePrimary = Color(0xFF2843F9)
val md_theme_dark_surfaceTint = Color(0xFFF57F17)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)


